server.port=8080

spring.application.name=codegraph

spring.datasource.url=jdbc:h2:file:./engine-data/db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# --- STORAGE CONFIG ---
# Where problem images will be stored
codegraph.storage.problem-images=uploads/problems

# --- MULTI-USER ISOLATED JUDGE SETTINGS ---
# All paths are relative to the executable for maximum portability
judge.workspace=./workspaces
judge.timeout-seconds=5
judge.java-memory=256m

# BUNDLED RUNTIME ISOLATION
# Point this to a folder named 'runtime' next to your executable
judge.bundled-jdk-path=./runtime

# Fallback paths (Only used if bundled-jdk-path folder is missing)
judge.java-path=java
judge.javac-path=javac

# --- SYSTEM SETTINGS ---
logging.level.root=INFO
logging.level.com.codegraph=DEBUG
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n
spring.jackson.serialization.indent-output=true
spring.devtools.restart.enabled=true
